import "./globals.css";
import { Poppins, Montserrat } from 'next/font/google';

const poppins = Poppins({ 
  subsets: ['latin'],
  weight: ['400'], // Define the weights you need
  variable: '--font-poppins',
});

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['500', '600', '700'],
  variable: '--font-montserrat',
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${montserrat.variable} antialiased ${SuppressedError}`  }
      >
        {children}
      </body>
    </html>
  );
}
